[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -rfbport 5900 -nopw -quiet
priority=20
startsecs=2
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/vesper-front/x11vnc.log
